title: GrainForge
email: work@bweichselbaum.de
name: "Benedict Weichselbaum"
description: "GrainForge is a software tool to digitalize film negatives and slides on macOS. Simple, streamlined, and affordable."
baseurl: ""
url: "https://grainforge.de"

encoding: UTF-8

plugins:
  - jekyll-seo-tag
